# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fFSoRHwvjSoB5SL8Ayp_-AhWKX3SoLS2

make sure the 'algorithms.py' file, train dataset as well as test dataset are in the same folder you are running this script in.
"""

from algorithms import *

train_path = "/content/MNIST_train.csv" #modify according to your train dataset path
test_path = "/content/MNIST_test.csv" #modify according to your test dataset path

dataset = Dataset(train_path,test_path)
train_image_data, train_labels, train_data = dataset.load_data('train')
train_image_data.shape, train_labels.shape
test_image_data, test_labels, test_data = dataset.load_data('test')

batch_size = 32
k = 5
classifier = simple_knn()
classifier.train(train_image_data, train_labels)

preds_knn = []
N = len(test_image_data)

for start in range(0, N, batch_size):
    end = min(start + batch_size, N)
    batch_idx = start // batch_size + 1
    total_batches = math.ceil(N / batch_size)
    predts = classifier.predict(test_image_data[start:end], k)
    preds_knn.extend(list(predts))

result = evaluate(test_labels, preds_knn)
print("Accuracy: {}, F1-score: {} for k ={}".format(result[0], result[1],k))
print("Completed predicting the test data.")